### ISSUE TITLE
How to switch evaluation environments between A, B, C and D?

### ISSUE THREAD

**Issue by ecielyang** [mees/calvin#109]
I want to evaluate model in A, B, C and D separately? Which parameter in which file should I adjust?

I notice that in calvin/dataset/task_D_D/task_D_D/merged_config.yaml, D is set:
```  
objects:
    fixed_objects:
      table:
        file: calvin_table_D/urdf/calvin_table_D.urdf
```
While in calvin/dataset/task_D_D/task_D_D/config.yaml, A is set:
```
scene:
  _target_: vr_env.scene.play_table_scene.PlayTableScene
  _recursive_: false
  name: calvin_scene_A
```
