### ISSUE TITLE
ModuleNotFoundError: No module named 'calvin_agent.datasets.play_data_module'

### ISSUE THREAD

**Issue by tarekdawey** [mees/calvin#57]
Hi,

I am trying to run this:  python evaluation/evaluate_policy.py --dataset_path /home/systemtec/calvin/dataset/task_D_D --train_folder /home/systemtec/calvin/D_D_static_rgb_baseline --checkpoint /home/systemtec/calvin/D_D_static_rgb_baseline/mcil_baseline.ckpt --debug

ModuleNotFoundError: No module named 'calvin_agent.datasets.play_data_module'

**Comment by tarekdawey** [comment]
Below is the pip list:

Package                       Version      Editable project location
----------------------------- ------------ ---------------------------------------
actionlib                     1.14.0
aiohttp                       3.8.6
aiosignal                     1.3.1
angles                        1.9.13
antlr4-python3-runtime        4.8
appdirs                       1.4.4
async-timeout                 4.0.3
attrs                         23.1.0
black                         23.10.0
bondpy                        1.8.6
Calvin                        0.0.1        /home/systemtec/calvin/calvin_models
calvin-env                    0.0.1        /home/systemtec/calvin/calvin_env
camera-calibration            1.17.0
camera-calibration-parsers    1.12.0
catkin                        0.8.10
certifi                       2023.7.22
cffi                          1.16.0
cfgv                          3.4.0
charset-normalizer            3.3.0
click                         8.1.7
cloudpickle                   3.0.0
cmake                         3.18.4
colorlog                      6.7.0
contourpy                     1.1.1
controller-manager            0.19.6
controller-manager-msgs       0.19.6
coverage                      7.3.2
cv-bridge                     1.16.2
cycler                        0.12.1
decorator                     4.4.2
diagnostic-analysis           1.11.0
diagnostic-common-diagnostics 1.11.0
diagnostic-updater            1.11.0
distlib                       0.3.7
docker-pycreds                0.4.0
dynamic-reconfigure           1.7.3
exceptiongroup                1.1.3
filelock                      3.12.4
flake8                        6.1.0
fonttools                     4.43.1
freetype-py                   2.4.0
frozenlist                    1.4.0
fsspec                        2023.9.2
gazebo_plugins                2.9.2
gazebo_ros                    2.9.2
gencpp                        0.7.0
geneus                        3.0.0
genlisp                       0.4.18
genmsg                        0.6.0
gennodejs                     2.0.2
genpy                         0.6.15
gitdb                         4.0.10
GitPython                     3.1.38
gym                           0.26.2
gym-notices                   0.0.8
huggingface-hub               0.17.3
hydra-colorlog                1.2.0
hydra-core                    1.1.1
identify                      2.5.30
idna                          3.4
image-geometry                1.16.2
imageio                       2.31.5
imageio-ffmpeg                0.4.9
importlib-metadata            6.8.0
importlib-resources           6.1.0
iniconfig                     2.0.0
interactive-markers           1.12.0
isort                         5.12.0
joblib                        1.3.2
joint-state-publisher         1.15.1
joint-state-publisher-gui     1.15.1
kiwisolver                    1.4.5
laser_geometry                1.6.7
lightning-lite                1.8.6
lightning-utilities           0.9.0
llvmlite                      0.41.0
lxml                          4.9.3
markdown-it-py                3.0.0
matplotlib                    3.7.3
mccabe                        0.7.0
mdurl                         0.1.2
message-filters               1.16.0
moveit-commander              1.1.13
moveit-core                   1.1.13
moveit-ros-planning-interface 1.1.13
moveit-ros-visualization      1.1.13
moviepy                       1.0.3
MulticoreTSNE                 0.1
multidict                     6.0.4
mypy                          1.6.1
mypy-extensions               1.0.0
networkx                      2.2
nltk                          3.8.1
nodeenv                       1.8.0
numba                         0.58.0
numpy                         1.24.4
numpy-quaternion              2022.4.3
nvidia-cublas-cu11            11.10.3.66
nvidia-cuda-nvrtc-cu11        11.7.99
nvidia-cuda-runtime-cu11      11.7.99
nvidia-cudnn-cu11             8.5.0.96
omegaconf                     2.1.2
opencv-python                 4.8.1.78
packaging                     23.2
pandas                        2.0.3
pathspec                      0.11.2
pathtools                     0.1.2
Pillow                        10.1.0
pip                           23.3.1
platformdirs                  3.11.0
plotly                        5.17.0
pluggy                        1.3.0
pre-commit                    3.5.0
proglog                       0.1.10
protobuf                      4.24.4
psutil                        5.9.6
pybullet                      3.2.5
pycodestyle                   2.11.1
pycollada                     0.6
pycparser                     2.21
pyflakes                      3.1.0
pyglet                        2.0.9
Pygments                      2.16.1
pyhash                        0.9.3
PyOpenGL                      3.1.0
pyparsing                     3.1.1
pyrender                      0.1.45
pytest                        7.4.2
pytest-cov                    4.1.0
python-dateutil               2.8.2
python-qt-binding             0.4.4
pytorch-lightning             1.8.6
pytz                          2023.3.post1
PyYAML                        6.0.1
qt-dotgraph                   0.4.2
qt-gui                        0.4.2
qt-gui-cpp                    0.4.2
qt-gui-py-common              0.4.2
regex                         2023.10.3
requests                      2.31.0
resource_retriever            1.12.7
rich                          13.6.0
rosbag                        1.16.0
rosboost-cfg                  1.15.8
rosclean                      1.15.8
roscreate                     1.15.8
rosgraph                      1.16.0
roslaunch                     1.16.0
roslib                        1.15.8
roslint                       0.12.0
roslz4                        1.16.0
rosmake                       1.15.8
rosmaster                     1.16.0
rosmsg                        1.16.0
rosnode                       1.16.0
rosparam                      1.16.0
rospy                         1.16.0
rosservice                    1.16.0
rostest                       1.16.0
rostopic                      1.16.0
rosunit                       1.15.8
roswtf                        1.16.0
rqt_action                    0.4.9
rqt_bag                       0.5.1
rqt_bag_plugins               0.5.1
rqt-console                   0.4.12
rqt_dep                       0.4.12
rqt_graph                     0.4.14
rqt_gui                       0.5.3
rqt_gui_py                    0.5.3
rqt-image-view                0.4.17
rqt_launch                    0.4.9
rqt-logger-level              0.4.12
rqt-moveit                    0.5.11
rqt_msg                       0.4.10
rqt_nav_view                  0.5.7
rqt_plot                      0.4.13
rqt_pose_view                 0.5.11
rqt_publisher                 0.4.10
rqt_py_common                 0.5.3
rqt_py_console                0.4.10
rqt-reconfigure               0.5.5
rqt-robot-dashboard           0.5.8
rqt-robot-monitor             0.5.15
rqt_robot_steering            0.5.12
rqt-runtime-monitor           0.5.10
rqt-rviz                      0.7.0
rqt_service_caller            0.4.10
rqt_shell                     0.4.11
rqt_srv                       0.4.9
rqt-tf-tree                   0.6.4
rqt_top                       0.4.10
rqt_topic                     0.4.13
rqt_web                       0.4.10
rviz                          1.14.20
safetensors                   0.4.0
scikit-learn                  1.3.1
scipy                         1.10.1
sensor-msgs                   1.13.1
sentence-transformers         2.2.2
sentencepiece                 0.1.99
sentry-sdk                    1.32.0
setproctitle                  1.3.3
setuptools                    57.5.0
six                           1.16.0
smach                         2.5.2
smach-ros                     2.5.2
smclib                        1.8.6
smmap                         5.0.1
somepackage                   1.2.3
srdfdom                       0.6.4
tacto                         0.0.3        /home/systemtec/calvin/calvin_env/tacto
tenacity                      8.2.3
tensorboardX                  2.6.2.2
termcolor                     2.3.0
tf                            1.13.2
tf-conversions                1.13.2
tf2-geometry-msgs             0.7.7
tf2-kdl                       0.7.7
tf2-py                        0.7.7
tf2-ros                       0.7.7
threadpoolctl                 3.2.0
tokenizers                    0.14.1
tomli                         2.0.1
topic-tools                   1.16.0
torch                         1.13.1
torchmetrics                  1.2.0
torchvision                   0.14.1
tqdm                          4.66.1
transformers                  4.34.0
trimesh                       4.0.0
typing_extensions             4.8.0
tzdata                        2023.3
urdfdom-py                    0.4.6
urdfpy                        0.0.22
urllib3                       2.0.7
virtualenv                    20.24.5
wandb                         0.15.12
wheel                         0.41.2
xacro                         1.14.16
yarl                          1.9.2
zipp                          3.17.0

**Comment by RamyE** [comment]
I have had to personally make some modifications to the config file and to the evaluate_policy_singlestep script to get it to run

**Comment by RamyE** [comment]
config.yaml after updates
```
callbacks:
  rollout:
    tasks:
      _target_: calvin_env.envs.tasks.Tasks
      tasks:
        rotate_red_block_right:
        - rotate_object
        - block_red
        - -60
        rotate_red_block_left:
        - rotate_object
        - block_red
        - 60
        rotate_blue_block_right:
        - rotate_object
        - block_blue
        - -60
        rotate_blue_block_left:
        - rotate_object
        - block_blue
        - 60
        rotate_pink_block_right:
        - rotate_object
        - block_pink
        - -60
        rotate_pink_block_left:
        - rotate_object
        - block_pink
        - 60
        push_red_block_right:
        - push_object
        - block_red
        - 0.1
        - 0
        push_red_block_left:
        - push_object
        - block_red
        - -0.1
        - 0
        push_blue_block_right:
        - push_object
        - block_blue
        - 0.1
        - 0
        push_blue_block_left:
        - push_object
        - block_blue
        - -0.1
        - 0
        push_pink_block_right:
        - push_object
        - block_pink
        - 0.1
        - 0
        push_pink_block_left:
        - push_object
        - block_pink
        - -0.1
        - 0
        move_slider_left:
        - move_door_rel
        - base__slide
        - 0.15
        move_slider_right:
        - move_door_rel
        - base__slide
        - -0.15
        open_drawer:
        - move_door_rel
        - base__drawer
        - 0.12
        close_drawer:
        - move_door_rel
        - base__drawer
        - -0.12
        lift_red_block_table:
        - lift_object
        - block_red
        - 0.05
        - table
        - base_link
        lift_red_block_slider:
        - lift_object
        - block_red
        - 0.03
        - table
        - plank_link
        lift_red_block_drawer:
        - lift_object
        - block_red
        - 0.05
        - table
        - drawer_link
        lift_blue_block_table:
        - lift_object
        - block_blue
        - 0.05
        - table
        - base_link
        lift_blue_block_slider:
        - lift_object
        - block_blue
        - 0.03
        - table
        - plank_link
        lift_blue_block_drawer:
        - lift_object
        - block_blue
        - 0.05
        - table
        - drawer_link
        lift_pink_block_table:
        - lift_object
        - block_pink
        - 0.05
        - table
        - base_link
        lift_pink_block_slider:
        - lift_object
        - block_pink
        - 0.03
        - table
        - plank_link
        lift_pink_block_drawer:
        - lift_object
        - block_pink
        - 0.05
        - table
        - drawer_link
        place_in_slider:
        - place_object
        - table
        - plank_link
        place_in_drawer:
        - place_object
        - table
        - drawer_link
        stack_block:
        - stack_objects
        unstack_block:
        - unstack_objects
        turn_on_lightbulb:
        - toggle_light
        - lightbulb
        - 0
        - 1
        turn_off_lightbulb:
        - toggle_light
        - lightbulb
        - 1
        - 0
        turn_on_led:
        - toggle_light
        - led
        - 0
        - 1
        turn_off_led:
        - toggle_light
        - led
        - 1
        - 0
        push_into_drawer:
        - push_object_into
        - - block_red
          - block_blue
          - block_pink
        - table
        - base_link
        - table
        - drawer_link
    _target_: calvin_agent.rollout.rollout.Rollout
    _recursive_: false
    env_cfg:
      _target_: calvin_env.envs.play_lmp_wrapper.PlayLMPWrapper
    skip_epochs: 1
    rollout_freq: 3
    video: true
    num_rollouts_per_task: 10
    check_percentage_of_batch: 1
    replan_freq: 30
    ep_len: 120
    empty_cache: true
    log_video_to_file: false
    save_dir: ./videos
    start_robot_neutral: false
    add_goal_thumbnail: true
    min_window_size: ${datamodule.datasets.vision_dataset.min_window_size}
    max_window_size: ${datamodule.datasets.vision_dataset.max_window_size}
    id_selection_strategy: select_longest
    lang_folder: ${datamodule.datasets.lang_dataset.lang_folder}
  checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: -1
    verbose: true
    monitor: val_act/action_loss_pp
    mode: min
    dirpath: saved_models
    filename: '{epoch}'
  tsne_plot:
    _target_: calvin_agent.visualization.tsne_plot.TSNEPlot
    perplexity: 40
    n_jobs: 8
    plot_percentage: 0.2
    opacity: 0.3
    marker_size: 5
  kl_schedule:
    _target_: calvin_agent.utils.kl_callbacks.KLConstantSchedule
datamodule:
  datasets:
    vision_dataset:
      _target_: calvin_agent.datasets.npz_dataset.NpzDataset
      key: vis
      save_format: npz
      batch_size: 32
      min_window_size: 16
      max_window_size: 32
      proprio_state: ${datamodule.proprioception_dims}
      obs_space: ${datamodule.observation_space}
      pad: true
      lang_folder: lang_annotations
    lang_dataset:
      _target_: calvin_agent.datasets.npz_dataset.NpzDataset
      key: lang
      save_format: npz
      batch_size: 32
      min_window_size: 16
      max_window_size: 32
      proprio_state: ${datamodule.proprioception_dims}
      obs_space: ${datamodule.observation_space}
      skip_frames: 1
      pad: true
      lang_folder: lang_annotations
  transforms:
    train:
      rgb_static:
      - _target_: torchvision.transforms.Resize
        size: 200
      - _target_: calvin_agent.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.5
        std:
        - 0.5
      - _target_: calvin_agent.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      rgb_gripper:
      - _target_: torchvision.transforms.Resize
        size: 84
      - _target_: calvin_agent.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.5
        std:
        - 0.5
      - _target_: calvin_agent.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      depth_static:
      - _target_: torchvision.transforms.Resize
        size: 200
      - _target_: calvin_agent.utils.transforms.AddDepthNoise
        shape:
        - 1000.0
        rate:
        - 1000.0
      - _target_: calvin_agent.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      depth_gripper:
      - _target_: torchvision.transforms.Resize
        size: 84
      - _target_: calvin_agent.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      rgb_tactile:
      - _target_: torchvision.transforms.Resize
        size: 70
      - _target_: torchvision.transforms.RandomCrop
        size: 64
      - _target_: calvin_agent.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.5
        std:
        - 0.5
      - _target_: calvin_agent.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      depth_tactile:
      - _target_: torchvision.transforms.Resize
        size: 64
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.1
        std:
        - 0.2
      - _target_: calvin_agent.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      robot_obs:
      - _target_: calvin_agent.utils.transforms.NormalizeVector
      - _target_: calvin_agent.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
      scene_obs:
      - _target_: calvin_agent.utils.transforms.NormalizeVector
      - _target_: calvin_agent.utils.transforms.AddGaussianNoise
        mean:
        - 0.0
        std:
        - 0.01
    val:
      rgb_static:
      - _target_: torchvision.transforms.Resize
        size: 200
      - _target_: calvin_agent.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.5
        std:
        - 0.5
      rgb_gripper:
      - _target_: torchvision.transforms.Resize
        size: 84
      - _target_: calvin_agent.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.5
        std:
        - 0.5
      depth_static:
      - _target_: torchvision.transforms.Resize
        size: 200
      depth_gripper:
      - _target_: torchvision.transforms.Resize
        size: 84
      rgb_tactile:
      - _target_: torchvision.transforms.Resize
        size: 70
      - _target_: torchvision.transforms.RandomCrop
        size: 64
      - _target_: calvin_agent.utils.transforms.ScaleImageTensor
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.5
        std:
        - 0.5
      depth_tactile:
      - _target_: torchvision.transforms.Resize
        size: 64
      - _target_: torchvision.transforms.Normalize
        mean:
        - 0.1
        std:
        - 0.2
      robot_obs:
      - _target_: calvin_agent.utils.transforms.NormalizeVector
      scene_obs:
      - _target_: calvin_agent.utils.transforms.NormalizeVector
  proprioception_dims:
    n_state_obs: 8
    keep_indices:
    - - 0
      - 7
    - - 14
      - 15
    robot_orientation_idx:
    - 3
    - 6
    normalize: true
    normalize_robot_orientation: true
  observation_space:
    rgb_obs:
    - rgb_static
    depth_obs: []
    state_obs:
    - robot_obs
    actions:
    - actions
    language:
    - language
  _target_: calvin_agent.datasets.calvin_data_module.CalvinDataModule
  _recursive_: false
  root_data_dir: /work/dlcsmall2/meeso-lfp_ws/calvin_data/task_D_D
  action_space: 7
  num_workers: 4
  action_max:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  action_min:
  - -1.0
  - -1.0
  - -1.0
  - -1.0
  - -1.0
  - -1.0
  - -1
  shuffle_val: false
model:
  perceptual_encoder:
    vision_static:
      _target_: calvin_agent.models.perceptual_encoders.vision_network.VisionNetwork
      input_width: 200
      input_height: 200
      activation_function: ReLU
      dropout_vis_fc: 0.0
      l2_normalize_output: false
      visual_features: 64
      num_c: 3
    vision_gripper: {}
    depth_static: {}
    depth_gripper: {}
    proprio:
      _target_: calvin_agent.models.perceptual_encoders.proprio_encoder.IdentityEncoder
      proprioception_dims: ${datamodule.proprioception_dims}
    tactile: {}
    _target_: calvin_agent.models.perceptual_encoders.concat_encoders.ConcatEncoders
    _recursive_: false
  plan_proposal:
    _target_: calvin_agent.models.plan_encoders.plan_proposal_net.PlanProposalNetwork
    perceptual_features: ???
    latent_goal_features: 32
    plan_features: 256
    activation_function: ReLU
    min_std: 0.0001
  plan_recognition:
    _target_: calvin_agent.models.plan_encoders.plan_recognition_net.PlanRecognitionNetwork
    in_features: ???
    plan_features: 256
    action_space: ${datamodule.action_space}
    birnn_dropout_p: 0.0
    min_std: 0.0001
  visual_goal:
    _target_: calvin_agent.models.encoders.goal_encoders.VisualGoalEncoder
    in_features: ???
    hidden_size: 2048
    latent_goal_features: 32
    l2_normalize_goal_embeddings: false
    activation_function: ReLU
  language_goal:
    _target_: calvin_agent.models.encoders.goal_encoders.LanguageGoalEncoder
    language_features: 384
    hidden_size: 2048
    latent_goal_features: 32
    word_dropout_p: 0.0
    l2_normalize_goal_embeddings: false
    activation_function: ReLU
  action_decoder:
    _target_: calvin_agent.models.decoders.logistic_policy_network.LogisticPolicyNetwork
    n_mixtures: 10
    hidden_size: 2048
    out_features: ${datamodule.action_space}
    log_scale_min: -7.0
    act_max_bound: ${datamodule.action_max}
    act_min_bound: ${datamodule.action_min}
    dataset_dir: ${datamodule.root_data_dir}
    policy_rnn_dropout_p: 0.0
    load_action_bounds: true
    num_classes: 256
    perceptual_features: ??
    latent_goal_features: 32
    plan_features: 256
  optimizer:
    _target_: torch.optim.Adam
    lr: ${training.lr}
  _target_: calvin_agent.models.mcil.MCIL
  _recursive_: false
  kl_beta: ${loss.kl_beta}
loss:
  kl_beta: 0.001
training:
  lr: 0.0001
trainer:
  gpus: 8
  precision: 16
  val_check_interval: 1.0
  max_epochs: 100
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: .
  name: play_lmp
  group: play_lmp
  log_model: false
  project: multi_play
  entity: multimodal_control
  id: ???
seed: 42
log_dir: ../
slurm: true
```
